#!/usr/bin/env bash
# Regenerate patches/*.patch from the pinned upstream sources.
#
# The patches are the AUDIT RECORD of exactly what this harness changed in a
# pinned upstream file. They are not consumed by the build -- `src/patched/*.sol`
# is compiled directly -- so nothing fails if they go stale, which is precisely
# why they are regenerated by a script rather than maintained by hand.
#
# Each patch documents two kinds of change and does not hide either:
#   1. the benchmark-only behaviour change (the fee constants), and
#   2. the import rewrites forced by the file living outside the vendored tree.
#
# Run ./script/fetch-vendor.sh first: the left-hand side must be the pinned file.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

if [[ ! -d lib/vendor ]]; then
  echo "error: lib/vendor is missing; run ./script/fetch-vendor.sh first" >&2
  exit 1
fi

emit() {
  local upstream="$1" patched="$2" out="$3"
  if [[ ! -f "$upstream" ]]; then
    echo "error: pinned source $upstream is missing" >&2
    exit 1
  fi
  # `--label` replaces the default `path<TAB>mtime` header. Without it the
  # header carries the file's modification time, fetch-vendor.sh rewrites that
  # time on every run, and the patch would then differ on every run -- leaving
  # the working tree dirty and every gas snapshot stamped `dirty: true`.
  #
  # diff exits 1 when the files differ, which is the expected case here.
  diff -u --label "$upstream" --label "$patched" "$upstream" "$patched" > "$out" || true
  if [[ ! -s "$out" ]]; then
    echo "error: $patched is identical to $upstream; the patch did not take effect" >&2
    exit 1
  fi
  local changed
  changed=$(grep -c '^[+-][^+-]' "$out" || true)
  echo "  $out ($changed changed lines)"
}

emit lib/vendor/univ2core/contracts/UniswapV2Pair.sol \
     src/patched/UniswapV2PairZeroFee.sol \
     patches/uniswap-v2-pair-zero-fee.patch

emit lib/vendor/univ2periphery/UniswapV2Library.sol \
     src/patched/UniswapV2LibraryZeroFee.sol \
     patches/uniswap-v2-library-zero-fee.patch

echo "ok"
