//! The Rust Flashbots port must reproduce every vector produced by executing the
//! pinned Solidity contract, integer-for-integer.
//!
//! `tests/fixtures/flashbots/golden-vectors.json` is generated by
//! `solidity/flashbots-golden/generate.sh`, which runs the real
//! `ExamplePropAmm` from flashbots/priority-update-registry @ da53117.
//! No expected value in this file comes from the Rust implementation.

use prop_amm_research::flashbots::FlashbotsPool;
use prop_amm_research::json::Json;
use prop_amm_research::u256::U256;

fn vectors() -> Json {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/flashbots/golden-vectors.json"
    );
    let text = std::fs::read_to_string(path).expect("read flashbots golden vectors");
    Json::parse(&text).expect("parse flashbots golden vectors")
}

fn field(vector: &Json, name: &str) -> U256 {
    let raw = vector
        .get(name)
        .unwrap_or_else(|| panic!("missing field {name}"))
        .as_num_str()
        .unwrap_or_else(|| panic!("field {name} is not a number"));
    U256::from_dec_str(raw).unwrap_or_else(|| panic!("field {name} does not fit in uint256"))
}

#[test]
fn port_matches_the_pinned_solidity_contract_exactly() {
    let json = vectors();
    let source = json.get("source").expect("provenance block");
    assert_eq!(
        source.get("commit").unwrap().as_str(),
        Some("da53117870c7bec96d71caebe1b3f94370aba3d6"),
        "vectors must come from the pinned commit"
    );

    let all = json.get("vectors").unwrap().as_array().unwrap();
    assert_eq!(
        all.len() as u64,
        json.get("count").unwrap().as_u64().unwrap(),
        "declared count must match the array"
    );
    assert!(all.len() >= 2_000, "expected a broad vector set");

    let mut x_to_y = 0usize;
    let mut y_to_x = 0usize;
    for vector in all {
        let name = vector.get("name").unwrap().as_str().unwrap();
        let pool = FlashbotsPool {
            concentration: field(vector, "concentration"),
            mult_x: field(vector, "multX"),
            mult_y: field(vector, "multY"),
            target_x: field(vector, "targetX"),
        };
        let reserve_x = field(vector, "reserveX");
        let amount_in = field(vector, "amountIn");
        let expected = field(vector, "amountOut");

        let direction = vector.get("direction").unwrap().as_str().unwrap();
        let actual = match direction {
            "XtoY" => {
                x_to_y += 1;
                pool.quote_x_to_y(reserve_x, amount_in)
            }
            "YtoX" => {
                y_to_x += 1;
                pool.quote_y_to_x(reserve_x, amount_in)
            }
            other => panic!("{name}: unknown direction {other}"),
        };
        assert_eq!(
            actual,
            Some(expected),
            "{name}: amountOut mismatch (reserveX={reserve_x}, amountIn={amount_in})"
        );
    }

    assert!(x_to_y > 0 && y_to_x > 0, "both directions must be covered");
}

#[test]
fn fixture_covers_the_parameter_pairing_table_and_off_target_reserves() {
    let json = vectors();
    let all = json.get("vectors").unwrap().as_array().unwrap();

    let mut seen_concentrations: Vec<String> = Vec::new();
    let mut above_target = 0usize;
    let mut below_target = 0usize;
    let mut at_target = 0usize;

    for vector in all {
        let concentration = vector.get("concentration").unwrap().as_num_str().unwrap();
        if !seen_concentrations.iter().any(|c| c == concentration) {
            seen_concentrations.push(concentration.to_string());
        }
        assert_eq!(
            field(vector, "multY"),
            U256::from_u128(1_000_000_000_000_000_000),
            "multY is pinned to 1e18 in this benchmark"
        );

        let reserve_x = field(vector, "reserveX");
        let target_x = field(vector, "targetX");
        if reserve_x > target_x {
            above_target += 1;
        } else if reserve_x < target_x {
            below_target += 1;
        } else {
            at_target += 1;
        }
    }

    for expected in ["1", "2", "5", "10", "20", "50", "100", "1000"] {
        assert!(
            seen_concentrations.iter().any(|c| c == expected),
            "pairing table concentration {expected} must be covered"
        );
    }
    assert!(at_target > 0, "reserveX == targetX states");
    assert!(above_target > 0, "reserveX > targetX states");
    assert!(below_target > 0, "reserveX < targetX states");
}
