//! `FullMath`, `SafeCast` and `LiquidityMath` against vectors produced by
//! executing the pinned Solidity.
//!
//! Fixtures: `tests/fixtures/u256/fullmath-solidity-vectors.json` and
//! `safecast-solidity-vectors.json`, generated by
//! `solidity/fullmath-vectors/generate.sh` against
//! Uniswap/v3-core `e3589b192d0be27e100cd0daaf6c97204fdb1899` at solc 0.7.6.
//!
//! Reverts are first-class here: a vector with `"reverted": true` asserts that
//! the Rust port returns `None`, and one with a result asserts the exact value.
//! An implementation that never reverted would fail just as loudly as one that
//! returned wrong numbers.

use prop_amm_research::json::Json;
use prop_amm_research::u256::{mul_div, mul_div_rounding_up, mul_mod, U256};
use prop_amm_research::univ3::signed::{to_uint160, I256};
use prop_amm_research::univ3::swap_math::add_delta;

fn load(name: &str) -> Json {
    let path = format!("{}/tests/fixtures/u256/{name}", env!("CARGO_MANIFEST_DIR"));
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    Json::parse(&text).unwrap_or_else(|e| panic!("parse {path}: {e}"))
}

fn hex(vector: &Json, field: &str) -> U256 {
    let raw = vector
        .get(field)
        .unwrap_or_else(|| panic!("missing field {field}"))
        .as_str()
        .unwrap_or_else(|| panic!("field {field} is not a string"));
    U256::from_hex_str(raw).unwrap_or_else(|| panic!("field {field} does not fit in uint256"))
}

fn expected(vector: &Json) -> Option<U256> {
    let value = vector.get("result").expect("result field");
    if value.is_null() {
        None
    } else {
        Some(
            U256::from_hex_str(value.as_str().expect("hex result"))
                .expect("result fits in uint256"),
        )
    }
}

fn reverted(vector: &Json) -> bool {
    vector
        .get("reverted")
        .expect("reverted field")
        .as_bool()
        .expect("bool")
}

fn check_provenance(json: &Json) {
    let source = json.get("source").expect("source block");
    assert_eq!(
        source.get("commit").unwrap().as_str(),
        Some("e3589b192d0be27e100cd0daaf6c97204fdb1899"),
        "vectors must come from the pinned v3-core commit"
    );
    assert_eq!(source.get("solc").unwrap().as_str(), Some("0.7.6"));
}

#[test]
fn full_math_matches_the_pinned_solidity_exactly() {
    let json = load("fullmath-solidity-vectors.json");
    check_provenance(&json);
    let vectors = json.get("vectors").unwrap().as_array().unwrap();
    assert_eq!(
        vectors.len() as u64,
        json.get("count").unwrap().as_u64().unwrap()
    );
    assert!(vectors.len() >= 1_000, "expected a broad vector set");

    let mut mul_div_seen = 0usize;
    let mut rounding_up_seen = 0usize;
    let mut reverts_seen = 0usize;
    let mut wide_products = 0usize;
    let mut rounding_overflows = 0usize;

    for vector in vectors {
        let name = vector.get("name").unwrap().as_str().unwrap();
        let a = hex(vector, "a");
        let b = hex(vector, "b");
        let denominator = hex(vector, "denominator");
        let function = vector.get("fn").unwrap().as_str().unwrap();

        let actual = match function {
            "mulDiv" => {
                mul_div_seen += 1;
                mul_div(a, b, denominator)
            }
            "mulDivRoundingUp" => {
                rounding_up_seen += 1;
                mul_div_rounding_up(a, b, denominator)
            }
            other => panic!("{name}: unknown function {other}"),
        };

        if reverted(vector) {
            reverts_seen += 1;
            assert_eq!(
                actual, None,
                "{name}: Solidity reverted but the port returned {actual:?}"
            );
        } else {
            assert_eq!(
                actual,
                expected(vector),
                "{name}: {function}({a}, {b}, {denominator})"
            );
        }

        // A product wider than 256 bits is the case a naive
        // checked_mul().checked_div() would get wrong; make sure the fixture
        // really exercises it.
        let product = a.full_mul(b);
        if product[4] != 0 || product[5] != 0 || product[6] != 0 || product[7] != 0 {
            wide_products += 1;
        }

        // The `require(result < type(uint256).max)` branch: mulDiv lands exactly
        // on the ceiling and there is a remainder, so the increment would wrap.
        // It is the narrowest revert in FullMath and the easiest to lose.
        if function == "mulDivRoundingUp"
            && !denominator.is_zero()
            && mul_div(a, b, denominator) == Some(U256::MAX)
            && mul_mod(a, b, denominator)
                .map(|r| !r.is_zero())
                .unwrap_or(false)
        {
            rounding_overflows += 1;
            assert!(
                reverted(vector),
                "{name}: mulDivRoundingUp must revert when the increment overflows"
            );
        }
    }

    assert!(mul_div_seen > 400, "mulDiv coverage");
    assert!(rounding_up_seen > 400, "mulDivRoundingUp coverage");
    assert!(reverts_seen > 50, "revert coverage: only {reverts_seen}");
    assert!(
        wide_products > 100,
        "only {wide_products} vectors had a 512-bit product; the phantom-overflow \
         path is the whole reason mulDiv exists"
    );
    assert!(
        rounding_overflows > 0,
        "the fixture no longer covers the mulDivRoundingUp increment-overflow revert"
    );
}

#[test]
fn mul_div_rounding_up_reverts_when_the_increment_would_overflow() {
    // Explicit, fixture-independent coverage of `require(result < type(uint256).max)`.
    //
    // a * b == 2^257 - 1 == 2 * MAX + 1, so with denominator 2:
    //   prod1 == 1 < 2          -> mulDiv does not revert
    //   floor(a*b / 2) == MAX   -> the result is exactly the ceiling
    //   (a*b) % 2 == 1          -> mulDivRoundingUp wants MAX + 1, which cannot fit
    //
    // The two factors are the composite halves of the Mersenne number 2^257 - 1,
    // chosen so that both fit in a uint256.
    let a = U256::from_dec_str("618298780995040089266257453058982480847").unwrap();
    let b = U256::from_dec_str("374550598501810936581776630096313181393").unwrap();
    let two = U256::from_u64(2);

    let product = a.full_mul(b);
    assert_eq!(
        U256::from_limbs([product[4], product[5], product[6], product[7]]),
        U256::ONE,
        "prod1 must be exactly 1 for this construction"
    );
    assert_eq!(
        mul_div(a, b, two),
        Some(U256::MAX),
        "mulDiv lands on the ceiling"
    );
    assert_eq!(mul_mod(a, b, two), Some(U256::ONE), "with a remainder");
    assert_eq!(
        mul_div_rounding_up(a, b, two),
        None,
        "so rounding up must revert rather than wrap to zero"
    );

    // One wei lower, the increment fits and must be taken.
    let three = U256::from_u64(3);
    let result = mul_div(a, b, three).expect("fits");
    assert!(result < U256::MAX);
    assert_eq!(
        mul_div_rounding_up(a, b, three),
        Some(result.checked_add(U256::ONE).unwrap()),
        "a remainder below the ceiling must round up"
    );
}

#[test]
fn safe_cast_and_liquidity_math_match_the_pinned_solidity_exactly() {
    let json = load("safecast-solidity-vectors.json");
    check_provenance(&json);
    let vectors = json.get("vectors").unwrap().as_array().unwrap();
    assert!(vectors.len() >= 200);

    let mut seen = [0usize; 4];
    for vector in vectors {
        let name = vector.get("name").unwrap().as_str().unwrap();
        let function = vector.get("fn").unwrap().as_str().unwrap();
        let is_revert = reverted(vector);

        match function {
            "toUint160" => {
                seen[0] += 1;
                let actual = to_uint160(hex(vector, "y"));
                if is_revert {
                    assert_eq!(actual, None, "{name}: expected a revert");
                } else {
                    assert_eq!(actual, expected(vector), "{name}");
                }
            }
            "toInt256" => {
                seen[1] += 1;
                let actual = I256::to_int256(hex(vector, "y"));
                if is_revert {
                    assert!(actual.is_none(), "{name}: expected a revert");
                } else {
                    assert_eq!(actual.map(|v| v.to_raw()), expected(vector), "{name}");
                }
            }
            "toInt128" => {
                seen[2] += 1;
                let actual = I256::from_raw(hex(vector, "y")).to_int128();
                if is_revert {
                    assert!(actual.is_none(), "{name}: expected a revert");
                } else {
                    let want = expected(vector).expect("result");
                    assert_eq!(
                        actual.map(|v| I256::from_i128(v).to_raw()),
                        Some(want),
                        "{name}"
                    );
                }
            }
            "addDelta" => {
                seen[3] += 1;
                let x = hex(vector, "x");
                let y = I256::from_raw(hex(vector, "y"));
                // addDelta takes uint128 x and int128 y; a vector outside those
                // ranges is not a valid call and the fixture does not contain one.
                let x128 = x.as_u128().expect("x fits uint128");
                let y128 = y.to_int128().expect("y fits int128");
                let actual = add_delta(x128, y128);
                if is_revert {
                    assert_eq!(actual, None, "{name}: expected 'LS' or 'LA'");
                } else {
                    assert_eq!(actual.map(U256::from_u128), expected(vector), "{name}");
                }
            }
            other => panic!("{name}: unknown function {other}"),
        }
    }

    for (index, label) in ["toUint160", "toInt256", "toInt128", "addDelta"]
        .into_iter()
        .enumerate()
    {
        assert!(seen[index] >= 40, "{label} coverage: only {}", seen[index]);
    }
}

#[test]
fn mul_div_rejects_exactly_what_solidity_rejects() {
    // Spot checks that do not depend on the fixture, so a fixture regression
    // cannot silently take these with it.
    let one = U256::ONE;
    let max = U256::MAX;

    // denominator == 0 reverts on both paths.
    assert_eq!(mul_div(one, one, U256::ZERO), None);
    assert_eq!(mul_div(max, max, U256::ZERO), None);
    assert_eq!(mul_div_rounding_up(one, one, U256::ZERO), None);

    // prod1 >= denominator reverts: 2^255 * 2^255 / 1 does not fit.
    let two_255 = U256::ONE.checked_shl(255).unwrap();
    assert_eq!(mul_div(two_255, two_255, one), None);

    // The largest result that does fit: MAX * MAX / MAX == MAX.
    assert_eq!(mul_div(max, max, max), Some(max));

    // Rounding up at the very top must revert rather than wrap.
    assert_eq!(mul_div_rounding_up(max, max, max), Some(max));
    let two = U256::from_u64(2);
    // (MAX * 2 - 1) / 2 rounds up to MAX... constructed via a denominator that
    // leaves a remainder at the ceiling.
    assert_eq!(
        mul_div_rounding_up(max, one, one),
        Some(max),
        "an exact division at the ceiling must not try to increment"
    );
    assert_eq!(mul_div(max, one, two), Some(max.shift_right(1)));
}
